
version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: rider_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - rider_network

  # Backend API Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: rider_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/rider_management?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 5000
      ML_SERVICE_URL: http://ml-service:5001
    depends_on:
      - mongodb
      - ml-service
    networks:
      - rider_network

  # ML Service
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: rider_ml_service
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://admin:password123@mongodb:27017/rider_management?authSource=admin
      PORT: 5001
    depends_on:
      - mongodb
    networks:
      - rider_network
    volumes:
      - ml_models:/app/models
      - ml_data:/app/data

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:5000/api
        REACT_APP_ML_SERVICE_URL: http://localhost:5001
    container_name: rider_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
      - ml-service
    networks:
      - rider_network

volumes:
  mongodb_data:
    driver: local
  ml_models:
    driver: local
  ml_data:
    driver: local

networks:
  rider_network:
    driver: bridge